name: Train

on:
  pull_request:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ serects.DOCKERHUB_USERNAME }}
        password: ${{secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Build and push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file:  ./Dockerfile
        push: true
        tags: ashivamdocker/ci_cd_docker:latest